export default {
  notAuthenticated: 'Not Authenticated',
  login: 'Github Login',
  authToken: 'Auth Token',
  authTokenLink: 'More Info Here',
  authButton: 'Authenticate',
  loading: 'Loading...',
  welcomTitle: 'Welcome %s',
  organization: 'Github Organization',
  find: 'Find',
  filter: 'Filter',
  orderBy: 'Order By',
  repositoryName: 'Repository Name',
  forkCount: 'Fork Count',
  commitsToMaster: 'Commits to master',
  author: 'Author',
  date: 'Date Commited',
  commitId: 'Commit Id',
  unAuth: 'Reset Auth Token',
  required: ' * required',
}
